name: CI Pipeline
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and test application
        run: mvn clean verify
        env:
          GITHUB_USER_REF: ${{ secrets.PACKAGE_REPO_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.PACKAGE_REPO_PASSWORD }}